trigger:
- master
- releases/*
- node6hotfixes/*

resources:

parameters:
- name: build_single_task
  displayName: Build Single Task
  type: boolean
  default: false
- name: task_name
  displayName: Task Name
  type: string
  default: TaskNameVN
- name: push_to_feed
  displayName: Push to Feed
  type: boolean
  default: false

jobs:
  # All tasks on Linux
  - job: build_all_linux
    displayName: Build all tasks (Linux)
    timeoutInMinutes: 180
    pool:
      vmImage: ubuntu-20.04
    steps:
    - template: ci/build-all-steps.yml
      parameters:
        os: Linux

  - job: buildSharedNpm_linux
    displayName: Build shared npm packages (Linux)
    pool:
      vmImage: ubuntu-20.04
    steps:
    - template: ci/build-common-npm.yml

